config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/index'
  get 'users/show'
  get 'share/index'
  root to: "static_pages#index"
  devise_for :users, path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'sign_up' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: %w[create update destroy]
  resources :shares, only: %w[index edit]

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %w[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  VALID_YOUTUBE_LINK_REGEX = /(?:https?:\/\/)?(?:www\.)?youtu\.?be(?:\.com)?\/?.*(?:watch|embed)?(?:.*v=|v\/|\/)([\w\-_]+)\&?/i

  has_many :votes, dependent: :destroy
  has_many :user_votes, through: :votes, source: :user

  belongs_to :user

  validates :link_youtube, presence: true,
    format: { with: VALID_YOUTUBE_LINK_REGEX }
  validates :description, length: { maximum: 1000 }, allow_blank: true

  before_save :get_embed_link_youtube

  scope :order_by_time,->(order) { order(created_at: order) }

  private
  def get_embed_link_youtube
    new_link_youtube = get_youtube_id(link_youtube)
    self.link_youtube = "https://youtube.com/embed/#{new_link_youtube}"
  end

  def get_youtube_id(link)
    id = ''
    url = link.gsub(/(>|<)/i,'').split(/(vi\/|v=|\/v\/|youtu\.be\/|\/embed\/)/)
    if url[2] != nil
      id = url[2].split(/[^0-9a-z_\-]/i)
      id = id[0];
    else
      id = url;
    end

    id
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable,
    :validatable
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name,  presence: true, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  class << self
    def search_by_name(keyword)
      keyword.present? ? where("name like ?", "%#{keyword}%") : all
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: %w[update destroy]

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "You shared a movie"
      redirect_to root_path
    else
      flash.now[:danger] = "You shared fail"
      render "shares/index"
    end
  end

  def update
    if @post.update post_params
      flash[:success] = "Movie updated successful"
      redirect_to root_path
    else
      flash.now[:danger] = "You shared fail"
      render "shares/edit"
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Movie deleted"
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:link_youtube, :description)
  end

  def find_post
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_path
      flash[:danger] = "Post not found"
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
  end

  def edit
    @post = Post.find_by(id: params[:id])
    unless @post
      redirect_to root_path
      flash[:danger] = "Post not found"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @all_posts = Post.all.includes(:user).order_by_time(:desc).paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: %w[show following followers]

  def index
    @users = User.search_by_name(params[:search]).paginate(page: params[:page], per_page: 12)
  end

  def show
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def following
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  def find_user
    @user = User.find_by(id: params[:id])
    unless @user
      redirect_to root_path
      flash[:danger] = "User not found"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user && user == current_user
  end

  def gravatar_for(user, options = { size: 80 }, class_name = 'img-xs rounded-circle')
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.name.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: class_name)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminatoInterview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",
      media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application",
      media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_more_info.html.erb
<div class="d-none d-xl-block col-xl-3 right-wrapper">
  <div class="row">
    <div class="col-md-12 grid-margin">
      <div class="card rounded">
          <div class="card-body">
            <h6 class="card-title">latest video</h6>
            <div class="latest-photos">
              <div class="row">
                <% @all_posts.limit(3).each do |post| %>
                  <div class="col-12">
                    <iframe class="w-100"
                      src="<%= post.link_youtube %>">
                    </iframe>
                  </div>
                  <hr />
                <% end %>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fas fa-home fa-lg fa-2x"></i>
      <b>Funny Movies</b>
    <% end %>

    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link #{controller_name == 'static_pages' ? 'active' : ''} d-flex flex-column text-center" do %>
            <i class="fas fa-home fa-lg"></i><span>Home</span>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link #{controller_name == 'users' ? 'active' : ''} d-flex flex-column text-center" do %>
              <i class="fas fa-users fa-lg"></i><span>Users</span>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to shares_path, class: "nav-link #{controller_name == 'shares' ? 'active' : ''} d-flex flex-column text-center" do %>
              <i class="fas fa-share-alt-square fa-lg"></i><span>Share</span>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle d-flex align-items-center"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <%= gravatar_for current_user, size: 150 %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <%= link_to "My profile", current_user, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link d-flex flex-column text-center #{controller_name == 'sessions' ? 'active' : ''}" do %>
              <i class="fas fa-sign-in-alt fa-lg"></i>
              <span>Login</span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/shared/_post.html.erb
<div class="col-md-12 grid-margin">
  <div class="card rounded">
    <div class="card-header">
      <div class="d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <%= gravatar_for post.user, size: 150 %>
          <div class="ms-3 d-flex flex-wrap align-items-center">
            <p class="mb-0 col-12"><%= post.user.name %></p>
            <p class="mb-0 col-12"><%= time_ago_in_words(post.created_at) %> ago.</p>
          </div>
        </div>
        <% if current_user?(post.user) %>
          <div class="dropdown">
            <button class="btn p-0 dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg pb-3px">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
              <%= link_to edit_share_path(post.id), class: "dropdown-item d-flex align-items-center" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-copy icon-sm mr-2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                </svg>
                <span class="ms-2">Edit</span>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: "You sure?" }, class: "dropdown-item d-flex align-items-center" do %>
                <i class="fas fa-trash fa-lg"></i>
                <span class="ms-3">Delete</span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <p class="mb-3 tx-14"><%= post.description %></p>
      <div class="position-relative custom-iframe-wrap">
        <iframe class="w-100 position-absolute custom-iframe"
          src="<%= post.link_youtube %>">
        </iframe>
      </div>
    </div>
  </div>
</div>

app/views/shared/_profile.html.erb
<div class="d-none d-md-block col-md-4 col-xl-3 left-wrapper">
  <div class="card rounded">
    <div class="card-body">
      <p class="text-center">Hope you enjoy the Funny Movies was shared here.</p>
      <% if user_signed_in? %>
        <div class="mt-3">
          <label class="tx-11 font-weight-bold mb-0 text-uppercase">Name:</label>
          <p class="text-muted"><%= current_user.name %></p>
        </div>
        <div class="mt-3">
          <label class="tx-11 font-weight-bold mb-0 text-uppercase">Follow info:</label>
          <%= render 'shared/stats' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>" class="ms-5">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shares/_form.html.erb
<%= form_for post, class: "" do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="mb-3 text-start">
    <%= f.label :link_youtube, class: "form-label" %>
    <%= f.text_field :link_youtube, class: "form-control bg-white" %>
  </div>
  <div class="mb-3 text-start">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control bg-white", rows: 6 %>
  </div>
  <%= f.submit yield(:button_title), class: "btn btn-primary text-white rounded" %>
<% end %>

app/views/shares/edit.html.erb
<% provide(:button_title, "Update") %>
<div class="container mt-7">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="w-50 m-auto p-5 border rounded bg-white text-center position-relative">
    <h3 class="text-center mb-4">Share a youtube movie</h3>
    <%= render "shares/form", post: @post %>
  </div>
</div>

app/views/shares/index.html.erb
<% provide(:button_title, "Share") %>
<div class="container mt-7">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="w-50 m-auto p-5 border rounded bg-white text-center position-relative">
    <h3 class="text-center mb-4">Share a youtube movie</h3>
    <%= render "shares/form", post: @post %>
  </div>
</div>

app/views/static_pages/_homepage_content.html.erb
<div class="col-md-8 col-xl-6 middle-wrapper">
  <div class="row">
    <% @all_posts.each do |post| %>
      <%= render "shared/post", post: post %>
    <% end %>
    <%= will_paginate @all_posts %>
    <% if @all_posts.length == 0 %>
      <div class="col-md-12 grid-margin">
        <div class="card rounded">
          <div class="card-header">
            No data to show
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="container mt-7">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="profile-page tx-13">
    <div class="row profile-body">
      <!-- left wrapper start -->
      <%= render "shared/profile" %>
      <!-- left wrapper end -->
      <!-- middle wrapper start -->
      <%= render "homepage_content" %>
      <!-- middle wrapper end -->
      <!-- right wrapper start -->
      <%= render "shared/more_info" %>
      <!-- right wrapper end -->
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <%= render 'unfollow', user: user %>
    <% else %>
      <%= render 'follow', user: user %>
    <% end %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
  html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/index.html.erb
<div class="container mt-7">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 offset-1">
        <div class="row mb-4">
          <div class="widget border-0">
            <%= form_tag users_path, method: :get do %>
              <div class="search">
                <%= text_field_tag :search, params[:search] , class: "form-control", placeholder: "Search Keywords" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row">
          <% @users.each do |user| %>
            <div class="col-sm-6 col-lg-4 mb-4">
              <div class="candidate-list candidate-grid">
                <div class="candidate-list-image">
                  <%= gravatar_for user, {size: 100}, 'img-fluid' %>
                </div>
                <div class="candidate-list-details">
                  <div class="candidate-list-info">
                    <div class="candidate-list-title">
                      <h5><%= link_to user.name, user %></h5>
                    </div>
                  </div>
                  <div class="candidate-list-favourite-time justify-content-center" style="height: 60px">
                    <%= render 'follow_form', user: user if user_signed_in? && current_user != user %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <%= will_paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-7">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= render 'follow_form', user: @user if user_signed_in? && current_user != @user %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
    <div class="col-md-8">
      <% if @user.posts.any? %>
        <h3>Funny Movies (<%= @user.posts.count %>)</h3>
        <div class="row">
          <% @posts.each do |post| %>
            <%= render "shared/post", post: post %>
          <% end %>
        </div>
        <%= will_paginate @posts %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="container mt-7">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= gravatar_for @user %>
        <h1><%= @user.name %></h1>
        <span><%= link_to "view my profile", @user %></span>
      </section>

      <section class="stats">
        <%= render 'shared/stats' %>
        <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
              <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
          </div>
        <% end %>
      </section>
    </aside>

    <div class="col-md-8">
      <h3><%= @title %></h3>
      <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>